---
- when: zrepl is defined
  block:
    - name: "Configure zrepl repository"
      vars:
        repos:
          - zrepl
        packages_present: "{{ __packages_present_zrepl__ }}"
        call_from: "zrepl role"
      ansible.builtin.import_role:
        name: "{{ __fqcn_pkg_role__ }}"
      tags: install

    - name: "Configure zrepl"
      become: true
      ansible.builtin.template:
        dest: /etc/zrepl/zrepl.yml
        src: zrepl.yml.j2
      notify: "Restart zrepl"
      tags:
        - config
        - configure
