---
- name: "Configure zrepl repository on RHEL"
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum_repository:
    name: zrepl
    description: ZREPL repository
    file: zrepl
    baseurl: https://zrepl.cschwarz.com/rpm/repo
    gpgkey: https://zrepl.cschwarz.com/rpm/rpm-key.asc
    gpgcheck: true

- name: "Configure zrepl repository on Debian"
  when: ansible_os_family == 'Debian'
  ansible.builtin.import_role:
    name: __fqcn_apt_role__
  vars:
    repos:
      - zrepl
